### ISSUE TITLE
Resizable window (height) for more toons

### ISSUE THREAD

**Issue by MaloDrex** [opussf/Rested-cf#2]
Hi,

Thanks a lot for this neat addon :D
Would you mind add a resizing handle at the botton of the window so we can resized it to display more toons at the same time?

There is a scroll handle, but it is not working (default camera zoom keys are bypassing it and it can't be handled too).

Thanks in advance for your help.
Best regards.

**Comment by opussf** [comment]
Hi,
I enabled the mouse wheel scrolling for now.
I'm going to make the resize a different issue, and address it soon.

Thanks!
